# Generated by Django 3.1.5 on 2021-03-12 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zestapi', '0003_auto_20210307_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participate',
            new_name='Booking',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='participants',
        ),
        migrations.AddField(
            model_name='ressource',
            name='bookings',
            field=models.ManyToManyField(through='zestapi.Booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
