# Generated by Django 3.1.5 on 2021-03-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zestapi', '0004_auto_20210312_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='ressource_id',
            new_name='share_id',
        ),
    ]
