# Generated by Django 3.1.5 on 2021-03-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zestapi', '0005_auto_20210324_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='share_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
