# Generated by Django 3.1.5 on 2021-03-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zestapi', '0005_userprofile'),
        ('zestapi', '0007_auto_20210326_1618'),
    ]

    operations = [
    ]
